name: Test reusable workflow performance

on:
  workflow_dispatch:

jobs:
  benchmarks:
    permissions:
      contents: read
      packages: write
    uses: clipper-registry/benchmarks/.github/workflows/push.yml@main
    with:
      buildkit_image: ghcr.io/clipper-registry/buildkit:latest
    secrets:
      CLIPPER_CI_CREDENTIALS: ${{ secrets.CLIPPER_CI_CREDENTIALS }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
